"""
Registrar -- CloudFormation Custom Resource that welds the Password Safe
managed account to the EC2 instance lifecycle.

  Create  -> wait for SSM readiness, read the per-instance SSH key
             AWS::EC2::KeyPair generated (environment.yaml), install its
             public half over SSM Run Command, onboard asset + managed
             system + managed account (carrying the private half), force an
             immediate rotation, reprocess both Smart Rules.
  Update  -> rotate + reprocess. Ids are stable.
  Delete  -> delete managed account and asset, reprocess. Idempotent; a
             missing object is success, not failure.

Why the key is read here rather than passed in from CloudFormation as a
plain value: a CFN parameter is visible in the console, in
`describe-stacks`, in the change set and in CloudTrail. AWS::EC2::KeyPair
instead stores the private half as an SSM SecureString that only this
function's role can decrypt; the only place the plaintext private key ever
exists is in this function's memory, briefly, en route to Password Safe.
After the first rotation (DSSAutoManagementFlag=true), even that seed key is
stale -- every key after it is generated by Password Safe itself.

DELETE MUST NOT THROW. A Custom Resource that fails on Delete leaves the
stack in DELETE_FAILED and a human has to go clean it up by hand. Every
failure on that path is logged and swallowed; orphan detection is the job of
scripts/reconcile.py, not of stack teardown.
"""

import json
import logging
import os
import time
import urllib.request
import secrets
import string

import boto3

import ec2_keypair
from passwordsafe import PasswordSafeClient, PasswordSafeError
from ssh_pubkey import openssh_public_key, KeyParseError

log = logging.getLogger()
log.setLevel(logging.INFO)

ssm = boto3.client("ssm")
secretsmanager = boto3.client("secretsmanager")

PS_BASE_URL = os.environ["PS_BASE_URL"]
PS_SECRET_ARN = os.environ["PS_SECRET_ARN"]

# Holds the functional account's PRIVATE key. Optional: if unset, the
# functional account must already exist in Password Safe and the registrar
# will only look it up, never create it.
PS_FUNCTIONAL_SECRET_ARN = os.environ.get("PS_FUNCTIONAL_SECRET_ARN") or None
FUNCTIONAL_PUBKEY_PARAM = os.environ.get(
    "FUNCTIONAL_PUBKEY_PARAM", "/ps-ephemeral/functional-account/public-key")

SSM_READY_TIMEOUT = int(os.environ.get("SSM_READY_TIMEOUT", "300"))
SSM_POLL_INTERVAL = 10
CMD_TIMEOUT = 120

CREATE_FAILED_SENTINEL = "CREATE_FAILED"


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def load_ps_credentials():
    """Bootstrap secret: the ONLY standing privilege in the whole design."""
    raw = secretsmanager.get_secret_value(SecretId=PS_SECRET_ARN)["SecretString"]
    doc = json.loads(raw)
    return doc["client_id"], doc["client_secret"]


def load_functional_credential():
    """
    Private half of the functional account's SSH key. Returns {} if no
    secret is configured, OR if the configured secret does not exist --
    in either case the functional account must already exist in Password
    Safe. ensure_functional_account() looks it up by name first and only
    needs these values on the create path, so a missing secret here is
    only fatal if the account also turns out not to exist.
    """
    if not PS_FUNCTIONAL_SECRET_ARN:
        return {}
    try:
        raw = secretsmanager.get_secret_value(
            SecretId=PS_FUNCTIONAL_SECRET_ARN)["SecretString"]
    except secretsmanager.exceptions.ResourceNotFoundException:
        log.info("functional account secret %s not found -- assuming the "
                  "functional account already exists in Password Safe",
                  PS_FUNCTIONAL_SECRET_ARN)
        return {}
    doc = json.loads(raw)
    return {
        "private_key": doc.get("private_key"),
        "passphrase": doc.get("passphrase"),
        "password": doc.get("password"),
    }


def read_public_key():
    """Public keys are not secrets, so this is a plain String parameter."""
    try:
        return ssm.get_parameter(Name=FUNCTIONAL_PUBKEY_PARAM)["Parameter"]["Value"]
    except ssm.exceptions.ParameterNotFound:
        return None


def generate_random_password(length=32):
    """Generate a secure random password for password-auth accounts."""
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    return ''.join(secrets.choice(alphabet) for _ in range(length))


def wait_for_ssm(instance_id):
    """
    The real readiness gate. DependsOn only tells you the RunInstances API
    returned -- it says nothing about whether the box has booted. If we onboard
    before the host answers, the Password Safe test-connection fails and we
    would hand the team an account they cannot use.
    """
    deadline = time.time() + SSM_READY_TIMEOUT
    while time.time() < deadline:
        resp = ssm.describe_instance_information(
            Filters=[{"Key": "InstanceIds", "Values": [instance_id]}]
        )
        info = resp.get("InstanceInformationList", [])
        if info and info[0].get("PingStatus") == "Online":
            log.info("instance %s online in SSM", instance_id)
            return
        time.sleep(SSM_POLL_INTERVAL)
    raise TimeoutError(
        f"{instance_id} did not register with SSM within {SSM_READY_TIMEOUT}s"
    )


def run_command(instance_id, commands):
    cmd = ssm.send_command(
        InstanceIds=[instance_id],
        DocumentName="AWS-RunShellScript",
        Parameters={"commands": commands},
        TimeoutSeconds=CMD_TIMEOUT,
    )["Command"]["CommandId"]

    deadline = time.time() + CMD_TIMEOUT
    while time.time() < deadline:
        time.sleep(3)
        try:
            inv = ssm.get_command_invocation(
                CommandId=cmd, InstanceId=instance_id
            )
        except ssm.exceptions.InvocationDoesNotExist:
            continue
        if inv["Status"] in ("Success",):
            return inv
        if inv["Status"] in ("Failed", "Cancelled", "TimedOut"):
            # StandardErrorContent is safe to log: the password goes in via
            # stdin heredoc and is never echoed by chpasswd.
            raise RuntimeError(
                f"SSM command {inv['Status']}: {inv.get('StandardErrorContent','')[:500]}"
            )
    raise TimeoutError(f"SSM command {cmd} did not finish in {CMD_TIMEOUT}s")


def provision_functional_account(instance_id, username, public_key,
                                 elevation="sudo"):
    """
    Create the functional account ON THE INSTANCE and install the public half
    of the key whose private half lives in Password Safe.

    user-data already does this at boot; doing it again here is deliberate.
    user-data is best-effort and silent when it fails, and if this account is
    missing or its key is wrong then the very first rotation fails -- leaving a
    vaulted credential that does not actually work. Better to converge it now,
    synchronously, while we can still fail the stack.

    Sudo is restricted to the two binaries a password change needs. Full
    NOPASSWD:ALL would make this account a fleet-wide root equivalent.
    """
    script = [
        "set -euo pipefail",
        f"id -u {username} >/dev/null 2>&1 || useradd -m -s /bin/bash {username}",
        f"install -d -m 700 -o {username} -g {username} /home/{username}/.ssh",
        f"cat > /home/{username}/.ssh/authorized_keys <<'PUBKEY'",
        public_key,
        "PUBKEY",
        f"chown {username}:{username} /home/{username}/.ssh/authorized_keys",
        f"chmod 600 /home/{username}/.ssh/authorized_keys",
        f"cat > /etc/sudoers.d/90-{username} <<'SUDO'",
        # grep/sed/tee are BeyondTrust's own documented requirement for the
        # functional account: SSH key auto-management removes the old public
        # key from authorized_keys (grep/sed) and appends the new one (tee).
        # chpasswd/passwd alone is only enough for PASSWORD rotation.
        f"{username} ALL=(root) NOPASSWD: /usr/sbin/chpasswd, /usr/bin/passwd, "
        f"/usr/bin/grep, /usr/bin/sed, /usr/bin/tee",
        "SUDO",
        f"chmod 440 /etc/sudoers.d/90-{username}",
        "visudo -c >/dev/null",
        # Fail loudly here rather than at first rotation.
        f"test -s /home/{username}/.ssh/authorized_keys",
    ]
    run_command(instance_id, script)
    log.info("functional account %s converged on %s", username, instance_id)


def provision_local_account_with_key(instance_id, username, public_key):
    """
    Create (or converge) the managed account itself and install the public
    half of a key AWS generated -- see environment.yaml's per-instance
    AWS::EC2::KeyPair. The private half went from SSM straight into this
    function's caller and then into the Password Safe API call; it is never
    written to disk, a template, or an instance.

    No special sudo for this account -- it is the account BEING managed, not
    an elevation identity. Password Safe writes this account's *next* key
    into this same file by logging in as the functional account and
    elevating with ITS sudo rule (provision_functional_account), not this
    one. If that elevation rule turns out to be too narrow for Linux DSS key
    rotation, that shows up here, not on this account.
    """
    script = [
        "set -euo pipefail",
        f"id -u {username} >/dev/null 2>&1 || useradd -m -s /bin/bash {username}",
        f"install -d -m 700 -o {username} -g {username} /home/{username}/.ssh",
        f"cat > /home/{username}/.ssh/authorized_keys <<'PUBKEY'",
        public_key,
        "PUBKEY",
        f"chown {username}:{username} /home/{username}/.ssh/authorized_keys",
        f"chmod 600 /home/{username}/.ssh/authorized_keys",
        # Key auth only for this account -- there is no password to fall
        # back to, so leaving password auth on would just be an unused,
        # unaudited second door.
        f"passwd -l {username} >/dev/null 2>&1 || true",
        f"test -s /home/{username}/.ssh/authorized_keys",
    ]
    run_command(instance_id, script)
    log.info("managed account %s key-provisioned on %s", username, instance_id)


def provision_local_account_with_password(instance_id, username, password):
    """
    Create (or converge) the managed account with password authentication.
    Password Safe will manage the password lifecycle via rotation.
    
    Enables SSH password authentication in sshd_config and sets the password
    via chpasswd (which never echoes the password to stdout/stderr).
    """
    script = [
        "set -euo pipefail",
        f"id -u {username} >/dev/null 2>&1 || useradd -m -s /bin/bash {username}",
        # Set password securely via stdin
        f"echo '{username}:{password}' | chpasswd",
        # Enable password authentication in SSH
        "sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config || true",
        "sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config || true",
        # Ensure PubkeyAuthentication is still on (for other accounts)
        "sed -i 's/^PubkeyAuthentication no/PubkeyAuthentication yes/' /etc/ssh/sshd_config || true",
        "systemctl restart sshd",
        # Verify account exists
        f"id -u {username} >/dev/null",
    ]
    run_command(instance_id, script)
    log.info("managed account %s password-provisioned on %s", username, instance_id)


def reprocess_rules(ps, cfg):
    """Best-effort: a rule that will not reprocess must not fail the stack."""
    for title in (cfg.get("smartRuleSystems"), cfg.get("smartRuleAccounts")):
        if not title:
            continue
        try:
            rule = ps.find_smart_rule(title)
            if rule:
                ps.process_smart_rule(rule["SmartRuleID"])
                log.info("reprocessed smart rule %s", title)
            else:
                log.warning("smart rule %r not found -- team will not see this "
                            "host until it exists", title)
        except PasswordSafeError as exc:
            log.warning("smart rule %s reprocess failed: %s", title, exc)


# --------------------------------------------------------------------------- #
# lifecycle
# --------------------------------------------------------------------------- #
def on_create(props):
    cfg = json.loads(props["Config"]) if isinstance(props["Config"], str) \
        else props["Config"]
    instance_id = props["InstanceId"]
    private_ip = props["PrivateIp"]
    asset_name = props["AssetName"]
    key_pair_id = props.get("KeyPairId")
    
    # Get passwordSafe config (allows both nested and root-level access)
    password_safe_cfg = cfg.get("passwordSafe", cfg)
    
    # Support both old single-account and new multi-account config formats
    accounts = password_safe_cfg.get("accounts", cfg.get("accounts", []))
    if not accounts:
        # Backward compatibility: convert single-account to array format
        accounts = [{
            "localAccountName": password_safe_cfg.get("localAccountName", cfg.get("localAccountName", "ec2-svc")),
            "authType": password_safe_cfg.get("authType", cfg.get("authType", "ssh_key")),
            "enableSSHKeyAuth": password_safe_cfg.get("enableSSHKeyAuth", cfg.get("enableSSHKeyAuth", True)),
        }]

    # Read functionalAccountName from nested functionalAccount object
    functional_name = password_safe_cfg.get("functionalAccountName", "ps-rotator")

    wait_for_ssm(instance_id)

    # 1. Functional account on the box, so Password Safe has a way in.
    functional_public_key = read_public_key()
    if functional_public_key:
        provision_functional_account(instance_id, functional_name,
                                     functional_public_key,
                                     password_safe_cfg.get("elevationCommand", "sudo"))
    else:
        log.warning("no public key at %s -- relying on user-data having "
                    "provisioned %s correctly", FUNCTIONAL_PUBKEY_PARAM,
                    functional_name)

    # 2. Provision each managed account
    account_metadata = {}
    
    for account in accounts:
        account_name = account.get("localAccountName", "ec2-svc")
        auth_type = account.get("authType", "ssh_key")
        
        if auth_type == "ssh_key":
            # SSH key-based authentication
            if not key_pair_id:
                raise ValueError(f"KeyPairId required for SSH key auth account {account_name}")
            
            private_key = ec2_keypair.read_private_key(ssm, key_pair_id)
            try:
                public_key = openssh_public_key(private_key, comment=account_name)
            except KeyParseError as exc:
                raise RuntimeError(f"could not derive public key from EC2 key pair "
                                   f"{key_pair_id}: {exc}") from exc
            provision_local_account_with_key(instance_id, account_name, public_key)
            account_metadata[account_name] = {
                "authType": "ssh_key",
                "private_key": private_key,
                "public_key": public_key,
            }
            
        elif auth_type == "password":
            # Password-based authentication
            password = generate_random_password()
            provision_local_account_with_password(instance_id, account_name, password)
            account_metadata[account_name] = {
                "authType": "password",
                "password": password,
            }
        else:
            raise ValueError(f"unknown authType {auth_type} for account {account_name}")

    client_id, client_secret = load_ps_credentials()
    with PasswordSafeClient(PS_BASE_URL, client_id, client_secret) as ps:
        wg = ps.get_workgroup(password_safe_cfg["workgroupName"])
        workgroup_id = wg.get("ID") or wg.get("WorkgroupID")
        platform = ps.get_platform(password_safe_cfg.get("platformName", "Linux"))
        platform_id = platform["PlatformID"]

        # 3. Functional account in the vault
        functional_account_id = ps.ensure_functional_account(
            platform, functional_name,
            elevation_command=password_safe_cfg.get("elevationCommand", "sudo"),
            description="ps-ephemeral-ec2 rotation identity",
            **load_functional_credential(),
        )

        # 4. Create managed system in the vault
        dss_key_rule_id = ps.get_dss_key_rule_id(password_safe_cfg.get("dssKeyRuleName"))
        system = ps.create_managed_system_in_workgroup(
            workgroup_id, platform_id, functional_account_id,
            system_name=asset_name,
            ip_address=private_ip,
            dns_name=props.get("PrivateDnsName") or asset_name,
            cfg={**password_safe_cfg, "dssKeyRuleId": dss_key_rule_id, "functionalAccountName": functional_name},
        )
        system_id = system["ManagedSystemID"]

        # 5. Create managed accounts in vault (one per instance account)
        physical_parts = []
        account_ids = []
        for account in accounts:
            account_name = account.get("localAccountName")
            auth_type = account.get("authType", "ssh_key")
            metadata = account_metadata.get(account_name, {})
            
            # Merge account-specific config with base config
            account_cfg = {**password_safe_cfg, **account, "functionalAccountName": functional_name}
            
            if auth_type == "ssh_key":
                managed_account = ps.create_managed_account(
                    system_id, account_name, account_cfg, platform=platform,
                    private_key=metadata["private_key"], workgroup_id=workgroup_id)
            else:
                managed_account = ps.create_managed_account(
                    system_id, account_name, account_cfg, platform=platform,
                    password=metadata["password"], workgroup_id=workgroup_id)
            
            account_id = managed_account["ManagedAccountID"]
            account_ids.append(str(account_id))
            physical_parts.append(f"{account_name}:{account_id}")
            
            # Force immediate rotation for SSH key accounts
            if auth_type == "ssh_key":
                try:
                    ps.rotate_credential(account_id)
                except PasswordSafeError as exc:
                    log.warning("INITIAL KEY ROTATION FAILED (%s) for %s. Check: (1) "
                                "the functional account can reach %s on port %s, "
                                "(2) its sudo rule can write %s's authorized_keys -- "
                                "see docs/RUNBOOK.md section 1b.", exc, account_name,
                                private_ip, password_safe_cfg.get("port", 22), account_name)
            else:
                log.info("password account %s created -- Password Safe will manage "
                         "password rotations per schedule", account_name)

        reprocess_rules(ps, password_safe_cfg)

    physical_id = f"{system_id}:{','.join(account_ids)}"
    log.info("onboarded %s as %s", asset_name, physical_id)
    return physical_id, {
        "ManagedSystemId": str(system_id),
        "ManagedAccountId": account_ids[0],
        "AccountName": accounts[0].get("localAccountName", ""),
        "ManagedAccounts": ",".join(physical_parts),
        "AssetName": asset_name,
        "Workgroup": password_safe_cfg["workgroupName"],
    }


def on_update(physical_id, props):
    """Ids are stable across updates -- never return a new PhysicalResourceId
    here, or CloudFormation will schedule a Delete on the old one."""
    cfg = json.loads(props["Config"]) if isinstance(props["Config"], str) \
        else props["Config"]
    password_safe_cfg = cfg.get("passwordSafe", cfg)
    
    try:
        parts = physical_id.split(":")
        system_id = parts[0]
        account_parts = [t for chunk in parts[1:]
                         for t in chunk.split(",") if t.isdigit()]
    except (ValueError, IndexError):
        log.warning("unparseable physical id %r on update -- no-op", physical_id)
        return physical_id, {}

    client_id, client_secret = load_ps_credentials()
    with PasswordSafeClient(PS_BASE_URL, client_id, client_secret) as ps:
        # Rotate all managed accounts
        for account_part in account_parts:
            try:
                account_id = account_part.split(":")[-1]
                ps.rotate_credential(int(account_id))
            except (ValueError, PasswordSafeError) as exc:
                log.warning("rotation on update failed for %s: %s", account_part, exc)
        reprocess_rules(ps, password_safe_cfg)
    
    return physical_id, {"ManagedAccounts": account_parts}


def on_delete(physical_id, props):
    """Never raises. See module docstring."""
    if not physical_id or physical_id.startswith(CREATE_FAILED_SENTINEL):
        log.info("nothing was ever created -- delete is a no-op")
        return

    try:
        parts = physical_id.split(":")
        system_id = parts[0]
        account_parts = [t for chunk in parts[1:]
                         for t in chunk.split(",") if t.isdigit()]
    except (ValueError, IndexError):
        log.warning("unparseable physical id %r -- nothing to deregister",
                    physical_id)
        return

    try:
        cfg = json.loads(props.get("Config", "{}")) if isinstance(props.get("Config"), str) \
            else props.get("Config", {})
        password_safe_cfg = cfg.get("passwordSafe", cfg)
        
        client_id, client_secret = load_ps_credentials()
        with PasswordSafeClient(PS_BASE_URL, client_id, client_secret) as ps:
            # Delete all managed accounts first, then the system
            for account_part in account_parts:
                try:
                    account_id = account_part.split(":")[-1]
                    ps.delete_managed_account(int(account_id))
                except (ValueError, PasswordSafeError) as exc:
                    log.error("failed to delete account %s: %s", account_part, exc)
            
            ps.delete_managed_system(int(system_id))
            
            if password_safe_cfg:
                reprocess_rules(ps, password_safe_cfg)
        log.info("deregistered %s", physical_id)
    except Exception as exc:                       # noqa: BLE001 - intentional
        log.error("DEREGISTRATION FAILED for %s: %s -- stack delete will "
                  "continue. Run scripts/reconcile.py to clean up the orphan.",
                  physical_id, exc)


# --------------------------------------------------------------------------- #
# CloudFormation plumbing
# --------------------------------------------------------------------------- #
def send_response(event, context, status, physical_id, data=None, reason=None):
    body = json.dumps({
        "Status": status,
        "Reason": reason or f"See CloudWatch log stream {context.log_stream_name}",
        "PhysicalResourceId": physical_id,
        "StackId": event["StackId"],
        "RequestId": event["RequestId"],
        "LogicalResourceId": event["LogicalResourceId"],
        "NoEcho": False,
        "Data": data or {},
    }).encode()

    req = urllib.request.Request(
        event["ResponseURL"], data=body, method="PUT",
        headers={"content-type": "", "content-length": str(len(body))},
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        log.info("cfn response %s -> %s", status, resp.status)


def lambda_handler(event, context):
    log.info("request: %s", json.dumps(
        {k: v for k, v in event.items() if k != "ResponseURL"}))

    request_type = event["RequestType"]
    props = event.get("ResourceProperties", {})
    physical_id = event.get("PhysicalResourceId")
    data = {}

    try:
        if request_type == "Create":
            physical_id, data = on_create(props)
        elif request_type == "Update":
            physical_id, data = on_update(physical_id, props)
        elif request_type == "Delete":
            on_delete(physical_id, props)
        else:
            raise ValueError(f"unknown RequestType {request_type}")

        send_response(event, context, "SUCCESS", physical_id, data)

    except Exception as exc:                       # noqa: BLE001
        log.exception("registrar failed")
        if request_type == "Delete":
            # Belt and braces: even an unexpected failure must not wedge the
            # stack in DELETE_FAILED.
            send_response(event, context, "SUCCESS",
                          physical_id or CREATE_FAILED_SENTINEL,
                          reason=f"delete tolerated failure: {exc}")
        else:
            send_response(event, context, "FAILED",
                          physical_id or CREATE_FAILED_SENTINEL,
                          reason=str(exc)[:900])
